### ISSUE TITLE
org.seasar.util#s2util;0.0.1: not found

### ISSUE THREAD

**Issue by intracer** [j5ik2o/scala-test-for-db-support#2]
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.seasar.util#s2util;0.0.1: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]          org.seasar.util:s2util:0.0.1 (/home/ilya/wmua/scalatestplus-db/build.sbt#L36-45)
[warn]            +- com.github.j5ik2o:scalatestplus-db_2.12:1.0.6-SNAPS

**Comment by j5ik2o** [comment]
Thank you for your reporting.This problem has been resolved
